---

- name: Ensure iptables is installed
  yum: name=iptables state=installed

- name: Put in place iptables configuration file from the template
  template:
    src: "iptables.j2"
    dest: "/etc/sysconfig/iptables"
    owner: "root"
    group: "root"
    mode: 600
  notify:
    - restart iptables

- name: Ensure iptables is enabled and will start at boot
  service: name=iptables state=started enabled=yes
